# Dockerfile for React client

# Stage 1
# Build react client
FROM node:17-alpine

# Working directory be app
WORKDIR /usr/src/app

COPY package*.json ./

###  Installing dependencies
RUN npm install --silent


# copy local files to app folder
COPY . .

RUN npm run build

# Stage 2
FROM nginx:1.17.0-alpine

COPY --from=build-stage /usr/src/app/build /usr/share/nginx/html

EXPOSE 3001

CMD nginx -g 'daemon off;'