export enum TEST_ACTION_TYPES {
  NEXT_QUESTION = "NEXT_QUESTION",
  PREVIOUS_QUESTION = "PREVIOUS_QUESTION",
  MARK_FOR_REVIEW = "MARK_FOR_REVIEW",
  MARK_FOR_REVIEW_AND_NEXT = "MARK_FOR_REVIEW_AND_NEXT",
  MARK_FOR_ANSWERED = "MARK_FOR_ANSWERED",
  SAVE_AND_NEXT = "SAVE_AND_NEXT",
  SAVE_AND_MARK_FOR_REVIEW = "SAVE_AND_MARK_FOR_REVIEW",
  MARK_FOR_NOT_ANSWERED = "MARK_FOR_NOT_ANSWERED",
}

export interface TEST_ACTION {
  type: TEST_ACTION_TYPES;
  payload: number; // index of question
}
